---
name: metal-stack component release

on:
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  draft:
    uses: metal-stack/actions-common/.github/workflows/release-drafter.yaml@v1

  spell-check:
    uses: metal-stack/actions-common/.github/workflows/spell-check.yaml@v1

  go-build:
    uses: metal-stack/actions-common/.github/workflows/go-build.yaml@v1
    secrets: inherit
    with:
      test-command: make test
      build-command: make token-refresher
